### ISSUE TITLE
Set Countdown Date And Time Not Updating

### ISSUE THREAD

**Issue by JohnPatrickAncajas** [RDjarbeng/countdown#130]
![image](https://github.com/RDjarbeng/countdown/assets/143093214/7342eb1b-518e-4ab6-b3ff-bd17acfc8a34)

The date and time displayed on the form do not automatically update, leading to a discrepancy with the actual current time. Similar to a previous issue at the today page.

**Comment by RDjarbeng** [comment]
The default behaviour of the form used to create a countdown should be to show the current date and time of the user. 
That date and time should not automatically updated since the user should be setting their own date and time. The user is expected to set a date and time, ideally some time in the future.


So I don't think it should auto update.

**Comment by RDjarbeng** [comment]
On the current behaviour, clicking submit without setting a countdown will create a countdown that will immediately elapse, which is not so useful. That might be an issue to be dealt with later.

**Comment by JohnPatrickAncajas** [comment]
Thank you sir! That is indeed an oversight on my part
