### ISSUE TITLE
Performance & Optimization

### ISSUE THREAD

**Issue by nyakotey** [RDjarbeng/countdown#44]
The project is growing fast and consequently performance begins to be a concern, #38 as an example. There is also need for more consistency in the project.
This is my suggestion:
when everything is set for v2(before deploying), there should be an optimization run where we will;
* organize the files into suitable folders
* agree on code spacing and pretty format all files (currently some are 2 spaces and others 4)
* remove redundant comment and code.
* optimize DOM manipulations (most performance issues come from this ) - analyze and take out unneeded manipulations
* refactor the files
&emsp; use BEM convention for the CSS, agree on method of getting DOM references and improve consistency

**Comment by nyakotey** [comment]
Also,every ongoing P&O issue can be logged in this thread

**Comment by nyakotey** [comment]
![Screenshot (356)](https://user-images.githubusercontent.com/73431750/152048731-0821a52c-9cb7-4c84-8a9a-5fa293e67a05.png)

`app.js` needs to be refactored. I'm sure infinite error logging will certainly impact performance. The reason for above is that `app.js` is included in the `countdown-list.html`, but since it doesn't have any clock stuff like `index.html`, it is causing the errors. If it is taken out, mode toggling doesn't work because functionality is defined in `app.js`

**Comment by RDjarbeng** [comment]
Organised files into folders in the refactor branch and built on from there in the VitePWA branch.
Moved related functions into js modules and imported them via `<script type="module" >
Separated UI functionality such as dark mode and others  from app.js.

Introduced bundling with viteJS so that ES6 syntax can be used across browser platforms.
Introduced Vite-plugin-pwa so we don't have to manually keep track of caching and service worker versions. 
Also added promt for update/new content using ToastifyJS so users can update to new version of the site without having to close all tabs first.

Current total application size upon build with viteJS approx. 2.94mb

**Comment by RDjarbeng** [comment]
Performance improvements expected with the latest release 2.5.0 #117  with bundling and precaching for a faster experience

**Comment by nyakotey** [comment]
On that note, I'm closing this issue.
It will be reopened should they arise later on
